import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/partials/header";
import Footer from "./components/partials/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={`${geistSans.variable} ${geistMono.variable} selection:bg-rose-500 selection:text-white`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
